#!/usr/bin/env python

import argparse
import os
import sys
import re
import shutil


BASE_DIR = os.path.expandvars("$HOME/Templates/")
INFO_FILE = os.path.join(BASE_DIR, "templates")
CURR_DIR = os.getcwd()


def print_templates():
    with open(INFO_FILE) as f:
        sys.stderr.write("\nAvialable Templates\n")
        sys.stderr.write(f.read())


class Parser(argparse.ArgumentParser):

    def print_help(self):
        super().print_help()
        print_templates()

    def error(self, message):
        self.print_help()
        sys.exit(2)

parser = Parser()
parser.add_argument(
        "project_name",
        type=str,
        help="The project name.")
parser.add_argument(
        "-t",
        type=str,
        default="note",
        help="Template to use (default: note)")

args = parser.parse_args()


try:
    project_loc = os.path.join(CURR_DIR, args.project_name + "/tex")
    shutil.copytree(os.path.join(BASE_DIR, args.t), project_loc)

    doc_file = os.path.join(project_loc, "doc.tex")
    proj_file = os.path.join(project_loc, args.project_name + ".tex")
    shutil.move(doc_file, proj_file)
except FileExistsError:
    sys.stderr.write("Project file already exists\n")
    sys.exit(2)
except FileNotFoundError:
    sys.stderr.write("Template not found\n")
    print_templates()
    sys.exit(2)


